codecov: 
 token: 43bc1506-855d-4b19-8f3f-770ce3a77f25
coverage:
  status:
    project:
      default:
        target: 90%    # the required coverage value
        threshold: 0.5%  # the leniency in hitting the target