name = "TaijaInteroperability"
uuid = "8949ac52-83c2-4a90-b175-e52cde45fddb"
authors = ["Patrick Altmeyer"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
