name = "TaijaInteroperability"
uuid = "8949ac52-83c2-4a90-b175-e52cde45fddb"
authors = ["Patrick Altmeyer"]
version = "0.1.0"

[deps]
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
CounterfactualExplanations = "2f13d31b-18db-44c1-bc43-ebaf2cff0be0"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
PackageExtensionCompat = "65ce6f38-6b18-4e1d-a461-8949797d7930"

[weakdeps]
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
RCall = "6f49c342-dc21-5d91-9882-a32aef131414"

[extensions]
PyTorchModelExt = "PythonCall"
RTorchModelExt = "RCall"

[compat]
CondaPkg = "0.2"
CounterfactualExplanations = "0.1"
Flux = "0.12, 0.13, 0.14"
julia = "1.7, 1.8, 1.9"
PackageExtensionCompat = "1"
